spring:
  messages:
    encoding: UTF-8
  application:
    name: receipts

  datasource:
    url: jdbc:postgresql://localhost:15432/db
    username: postgres
    password: postgres
  sql:
    init:
      mode: always
      data-locations: data.sql

  jpa:
    open-in-view: false
    generate-ddl: false
    hibernate:
      ddl-auto: none

    show-sql: true

logging:
  level:
    ROOT: ERROR
