server:
  port: 8181

spring:
  application:
    name: receipts
  messages:
    encoding: UTF-8
  data:
    mongodb:
      port: 2888
      database: receipts
      host: localhost
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9888/eureka/

logging:
  level:
    ROOT: ERROR
