server:
  port: 8181

spring:
  application:
    name: receipts
  messages:
    encoding: UTF-8
  cloud:
    openfeign:
      oauth2:
        enabled: true
        clientRegistrationId: keycloak
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8484/realms/product_realm
            token-uri: http://localhost:8484/realms/product_realm/protocol/openid-connect/token
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: product_client
            client-secret: YRQGQrD7tJbOOGdkuyu1z4jbnQ1h9V5u
            authorization-grant-type: authorization_code
            provider: keycloak
            scope:
              - openid
              - profile
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8484/realms/product_realm/protocol/openid-connect/certs

  datasource:
    url: jdbc:postgresql://localhost:15432/productsDb
    username: productUser
    password: prodPwdDb
  sql:
    init:
      mode: always

  jpa:
    open-in-view: false
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9888/eureka/

logging:
  level:
    ROOT: ERROR
