create table if not exists foods (
    id integer generated by default as identity,
    name varchar(255),
    primary key (id)
);

create table if not exists mealtime_types (
    id integer generated by default as identity,
    name varchar(255),
    primary key (id)
);

create table if not exists receipts (
    id integer generated by default as identity,
    food_id bigint references foods (id) on delete cascade,
    instruction varchar(255),
    primary key (id)
);

create table if not exists match_receipt_to_meal (
    id integer generated by default as identity,
    receipt_id bigint references receipts (id) on delete cascade,
    mealtime_type_id bigint references mealtime_types (id) on delete cascade,
    primary key (id)
);

create table if not exists servings (
    id integer generated by default as identity,
    name varchar(255),
    food_id bigint references foods (id) on delete cascade,
    calories decimal,
    proteins decimal,
    fats decimal,
    carbohydrates decimal,
    primary key (id)
);

create table if not exists ingredient (
    id integer generated by default as identity,
    receipt_id bigint references receipts (id) on delete cascade,
    serving_id bigint references servings (id) on delete cascade,
    quantity decimal,
    primary key (id)
);
