drop table if exists foods cascade;
drop table if exists diets cascade;
drop table if exists calories cascade;
drop table if exists mealtime_types cascade;
drop table if exists receipts cascade;
drop table if exists servings cascade;
drop table if exists ingredient cascade;
drop table if exists meals cascade;
drop table if exists meal_position cascade;

create table if not exists foods
(
    id   integer generated by default as identity,
    name varchar(255),
    primary key (id)
);

create table if not exists diets
(
    id   integer generated by default as identity,
    name varchar(255),
    primary key (id)
);

create table if not exists calories
(
    id       integer generated by default as identity,
    calories decimal,
    primary key (id)
);

create table if not exists mealtime_types
(
    id   integer generated by default as identity,
    name varchar(255),
    primary key (id)
);

create table if not exists receipts
(
    id          integer generated by default as identity,
    food_id     bigint references foods (id) on delete cascade,
    instruction varchar(255),
    primary key (id)
);

create table if not exists servings
(
    id            integer generated by default as identity,
    name          varchar(255),
    food_id       bigint references foods (id) on delete cascade,
    calories      decimal,
    proteins      decimal,
    fats          decimal,
    carbohydrates decimal,
    primary key (id)
);

create table if not exists receipt_positions
(
    id         integer generated by default as identity,
    receipt_id bigint references receipts (id) on delete cascade,
    serving_id bigint references servings (id) on delete cascade,
    quantity   decimal,
    primary key (id)
);

create table if not exists meals
(
    id               integer generated by default as identity,
    mealtime_type_id bigint references mealtime_types (id) on delete cascade,
    diet_id          bigint references diets (id) on delete cascade,
    calories_id      bigint references calories (id) on delete cascade,
    primary key (id)
);

create table if not exists meal_positions
(
    id         integer generated by default as identity,
    meal_id bigint references meals (id) on delete cascade,
    serving_id bigint references servings (id) on delete cascade,
    quantity decimal,
    primary key (id)
);
