create table if not exists authors (
    id integer generated by default as identity,
    full_name varchar(255),
    primary key (id)
);

create table if not exists genres (
    id integer generated by default as identity,
    name varchar(255),
    primary key (id)
);

create table if not exists books (
    id integer generated by default as identity,
    title varchar(255),
    author_id bigint references authors (id) on delete cascade,
    genre_id bigint references genres(id) on delete cascade,
    primary key (id)
);

create table if not exists comments (
    id integer generated by default as identity,
    book_id bigint references books (id) on delete cascade,
    text varchar(255)
);
