server:
  port: 8282

spring:
  application:
    name: meal-configurator
  messages:
    encoding: UTF-8
  data:
    mongodb:
      port: 2888
      database: day-meals
      host: localhost

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8484/auth/realms/meals.keycloak
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9888/eureka/

logging:
  level:
    ROOT: ERROR
