name: Build

on:
  pull_request:
    branches: [main]
    types: [opened, reopened, edited, ready_for_review, review_requested]

jobs:
  build-app:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repo
        uses: actions/checkout@v4
    
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build application
        run: |
          mvn verify --no-transfer-progress
